// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjtSI0VrtjTdg0MGYzE3ONUvNv3ICohg',
    appId: '1:544558700509:web:04e00ff1aa2bf93687c834',
    messagingSenderId: '544558700509',
    projectId: 'prueba2-a9de4',
    authDomain: 'prueba2-a9de4.firebaseapp.com',
    storageBucket: 'prueba2-a9de4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARIO4WE-OBbGBWEoVPI3Qb2bcKZoWgDX0',
    appId: '1:544558700509:android:59a53047904a9d2487c834',
    messagingSenderId: '544558700509',
    projectId: 'prueba2-a9de4',
    storageBucket: 'prueba2-a9de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1zvKTbRqP6OABnus2Vl01y1vRdVR4yzE',
    appId: '1:544558700509:ios:79224fa9a74f08c187c834',
    messagingSenderId: '544558700509',
    projectId: 'prueba2-a9de4',
    storageBucket: 'prueba2-a9de4.firebasestorage.app',
    iosBundleId: 'com.example.prueba2',
  );
}
